# -*- coding: utf-8 -*-
"""VBA_Menden.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTTv-uKdbvA-Iz29ef2KNOeJpxBl2yDD
"""

import io, re, zipfile, requests
import pandas as pd
from datetime import date

STATION_ID = "05705"  # Würzburg
BASE_URL = "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/kl/"
CUTOFF = date.today()  # Stoppdatum = heute

def download_zip(url):
    print(f"→ Lade: {url}")
    r = requests.get(url, timeout=30)
    r.raise_for_status()
    return zipfile.ZipFile(io.BytesIO(r.content))

def read_zip(zf):
    data_file = [f for f in zf.namelist() if f.startswith("produkt_")][0]
    with zf.open(data_file) as f:
        df = pd.read_csv(f, sep=";", encoding="latin-1")
    return df

# Download recent
zf_recent = download_zip(f"{BASE_URL}recent/tageswerte_KL_{STATION_ID}_akt.zip")
df_recent_raw = read_zip(zf_recent)

# Download historical
base_hist = BASE_URL + "historical/"
r = requests.get(base_hist, timeout=30)
pattern = rf"tageswerte_KL_{STATION_ID}_\d{{8}}_\d{{8}}_hist\.zip"
filename = re.findall(pattern, r.text)[0]
zf_hist = download_zip(base_hist + filename)
df_hist_raw = read_zip(zf_hist)

print("\nRecent - Spalten:")
print(df_recent_raw.columns.tolist())
print("\nRecent - Erste 3 Zeilen:")
print(df_recent_raw.head(3))

# Combine historical + recent into one raw dataframe
df_all_raw = pd.concat([df_hist_raw, df_recent_raw], ignore_index=True)

# Clean column names (remove spaces)
df_all_raw.columns = df_all_raw.columns.str.strip()

# Parse date and set as index
df_all_raw["MESS_DATUM"] = pd.to_datetime(df_all_raw["MESS_DATUM"], format="%Y%m%d")
df_all_raw = df_all_raw.set_index("MESS_DATUM").sort_index()

# Replace DWD error values with NaN
df_all_raw = df_all_raw.replace(-999.0, float("nan"))
df_all_raw = df_all_raw.replace(-999, float("nan"))

# Cut off at today
df_all_raw = df_all_raw[df_all_raw.index.date <= CUTOFF]

# Remove duplicates
df_all_raw = df_all_raw[~df_all_raw.index.duplicated(keep="last")]

print("Kombinierte Rohdaten bereit!")
print(f"Zeitraum: {df_all_raw.index[0].date()} bis {df_all_raw.index[-1].date()}")
print(f"Anzahl Tage: {len(df_all_raw)}")

# ── KENIA: Wind ──────────────────────────────────────────────
df_wind = df_all_raw[["FM", "FX"]].copy()
df_wind.columns = ["windgeschwindigkeit_ms", "windspitze_ms"]
df_wind = df_wind.dropna(how="all")

# ── Jonas: Luftdruck ─────────────────────────────────────
df_druck = df_all_raw[["PM"]].copy()
df_druck.columns = ["luftdruck_hpa"]
df_druck = df_druck.dropna()

# ── Clara: Temperatur ────────────────────────────────────
df_temp = df_all_raw[["TMK", "TXK", "TNK"]].copy()
df_temp.columns = ["temperatur_mittel_c", "temperatur_max_c", "temperatur_min_c"]
df_temp = df_temp.dropna(how="all")

# ── Zusammenfassung ──────────────────────────────────────────
print("=" * 50)
print("WIND (Kenia):")
print(f"  Zeitraum: {df_wind.index[0].date()} bis {df_wind.index[-1].date()}")
print(f"  Beobachtungen: {len(df_wind)}")
print(f"  Fehlende Werte:\n{df_wind.isna().sum()}")

print("\nLUFTDRUCK (Jonas):")
print(f"  Zeitraum: {df_druck.index[0].date()} bis {df_druck.index[-1].date()}")
print(f"  Beobachtungen: {len(df_druck)}")
print(f"  Fehlende Werte:\n{df_druck.isna().sum()}")

print("\nTEMPERATUR (Clara):")
print(f"  Zeitraum: {df_temp.index[0].date()} bis {df_temp.index[-1].date()}")
print(f"  Beobachtungen: {len(df_temp)}")
print(f"  Fehlende Werte:\n{df_temp.isna().sum()}")

import matplotlib.pyplot as plt

fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=False)

# ── Wind (Kenia) ─────────────────────────────────────────────
axes[0].plot(df_wind["windgeschwindigkeit_ms"], linewidth=0.5, color="steelblue")
axes[0].set_title("Windgeschwindigkeit – Würzburg (1966–2026)", fontsize=12)
axes[0].set_ylabel("m/s")

# ── Luftdruck (Jonas) ────────────────────────────────────
axes[1].plot(df_druck["luftdruck_hpa"], linewidth=0.5, color="tomato")
axes[1].set_title("Luftdruck – Würzburg (1947–2026)", fontsize=12)
axes[1].set_ylabel("hPa")

# ── Temperatur (Clara) ───────────────────────────────────
axes[2].plot(df_temp["temperatur_mittel_c"], linewidth=0.5, color="seagreen")
axes[2].set_title("Temperatur – Würzburg (1947–2026)", fontsize=12)
axes[2].set_ylabel("°C")

plt.tight_layout()
plt.show()

# SCHRITT 1: DATENBEREINIGUNG – Wind Geschwindigkeit (FM)

import pandas as pd
import numpy as np

# Nur FM aus df_wind extrahieren
wind = df_wind["windgeschwindigkeit_ms"].copy()

print("Vor der Bereinigung")
print(f"Zeitraum:          {wind.index[0].date()} bis {wind.index[-1].date()}")
print(f"Anzahl Werte:      {len(wind)}")
print(f"Fehlende Werte:    {wind.isna().sum()}")
print(f"Negative Werte:    {(wind < 0).sum()}")
print(f"Nullwerte:         {(wind == 0).sum()}")
print(f"\nErste 5 Zeilen:\n{wind.head()}")

# ── Fehlende Werte behandeln ─────────────────────────────────
# Methode: lineare Interpolation (da nur 12 fehlende Tage)
wind_clean = wind.interpolate(method="linear")

# ── Sicherstellen dass kein negativer Wert existiert ─────────
wind_clean = wind_clean.clip(lower=0)

# ── Vollständigen Datumsindex sicherstellen ──────────────────
# (falls einzelne Tage komplett fehlen)
full_index = pd.date_range(
    start=wind_clean.index[0],
    end=wind_clean.index[-1],
    freq="D"
)
wind_clean = wind_clean.reindex(full_index)
wind_clean = wind_clean.interpolate(method="linear")

print("\n Nach der Bereinigung")
print(f"Zeitraum:          {wind_clean.index[0].date()} bis {wind_clean.index[-1].date()}")
print(f"Anzahl Werte:      {len(wind_clean)}")
print(f"Fehlende Werte:    {wind_clean.isna().sum()}")
print(f"Negative Werte:    {(wind_clean < 0).sum()}")
print(f"\nErste 5 Zeilen:\n{wind_clean.head()}")

# SCHRITT 2: DESKRIPTIVE ANALYSE – Wind Geschwindigkeit (FM)

import pandas as pd
import numpy as np

# ── Grundlegende Statistiken ─────────────────────────────────
print("Deskriptive Statistiken\n")

stats = pd.DataFrame({
    "Kennzahl": [
        "Anzahl Beobachtungen",
        "Mittelwert (m/s)",
        "Median (m/s)",
        "Standardabweichung (m/s)",
        "Minimum (m/s)",
        "Maximum (m/s)",
        "25% Quantil (m/s)",
        "75% Quantil (m/s)",
        "Schiefe (Skewness)",
        "Wölbung (Kurtosis)"
    ],
    "Wert": [
        len(wind_clean),
        round(wind_clean.mean(), 4),
        round(wind_clean.median(), 4),
        round(wind_clean.std(), 4),
        round(wind_clean.min(), 4),
        round(wind_clean.max(), 4),
        round(wind_clean.quantile(0.25), 4),
        round(wind_clean.quantile(0.75), 4),
        round(wind_clean.skew(), 4),
        round(wind_clean.kurt(), 4)
    ]
})

print(stats.to_string(index=False))

# ── Analyse nach Jahrzehnt ───────────────────────────────────
print("\n Mittelwert pro Jahrzehnt \n")

wind_df = wind_clean.to_frame(name="FM")
wind_df["Jahrzehnt"] = (wind_df.index.year // 10) * 10
jahrzehnt = wind_df.groupby("Jahrzehnt")["FM"].agg(
    Mittelwert="mean",
    Std="std",
    Min="min",
    Max="max"
).round(3)

print(jahrzehnt.to_string())

# ── Analyse nach Monat ───────────────────────────────────────
print("\n Mittelwert pro Monat \n")

wind_df["Monat"] = wind_df.index.month
monate = {1:"Jan", 2:"Feb", 3:"Mär", 4:"Apr", 5:"Mai", 6:"Jun",
          7:"Jul", 8:"Aug", 9:"Sep", 10:"Okt", 11:"Nov", 12:"Dez"}

monat_stats = wind_df.groupby("Monat")["FM"].agg(
    Mittelwert="mean",
    Std="std",
    Min="min",
    Max="max"
).round(3)
monat_stats.index = monat_stats.index.map(monate)

print(monat_stats.to_string())

"""Daten sind right skwed, was auf grosse Ausreisser hinweisst.
Wind Bescreibung laut der Beaufort Skala: https://www.iwr.de/wind/klima/beaufort-skala.html
"""

# SCHRITT 3: DATENVISUALISIERUNG – Wind Geschwindigkeit (FM)

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np

fig = plt.figure(figsize=(16, 20))
gs = gridspec.GridSpec(4, 2, figure=fig, hspace=0.4, wspace=0.3)

# ── Plot 1: Zeitreihe komplett ───────────────────────────────
ax1 = fig.add_subplot(gs[0, :])
ax1.plot(wind_clean, linewidth=0.4, color="steelblue", alpha=0.8)
ax1.set_title("Windgeschwindigkeit Würzburg 1966–2026 (Tagesmittel)", fontsize=13)
ax1.set_ylabel("m/s")
ax1.set_xlabel("Jahr")

# ── Plot 2: Jahresmittelwerte ────────────────────────────────
ax2 = fig.add_subplot(gs[1, :])
jahres_mittel = wind_clean.resample("YE").mean()
ax2.bar(jahres_mittel.index.year, jahres_mittel.values,
        color="steelblue", alpha=0.7, width=0.8)
ax2.axhline(wind_clean.mean(), color="tomato", linestyle="--",
            linewidth=1.2, label=f"Gesamtmittel: {wind_clean.mean():.2f} m/s")
ax2.set_title("Jahresmittelwerte der Windgeschwindigkeit", fontsize=13)
ax2.set_ylabel("m/s")
ax2.set_xlabel("Jahr")
ax2.legend()

# ── Plot 3: Monatliche Saisonalität ─────────────────────────
ax3 = fig.add_subplot(gs[2, 0])
wind_df = wind_clean.to_frame(name="FM")
wind_df["Monat"] = wind_df.index.month
monat_mittel = wind_df.groupby("Monat")["FM"].mean()
monate_labels = ["Jan","Feb","Mär","Apr","Mai","Jun",
                 "Jul","Aug","Sep","Okt","Nov","Dez"]
ax3.bar(monate_labels, monat_mittel.values, color="steelblue", alpha=0.7)
ax3.set_title("Durchschnittliche Windgeschwindigkeit pro Monat", fontsize=12)
ax3.set_ylabel("m/s")
ax3.set_xlabel("Monat")

# ── Plot 4: Histogramm ───────────────────────────────────────
ax4 = fig.add_subplot(gs[2, 1])
ax4.hist(wind_clean, bins=50, color="steelblue", alpha=0.7, edgecolor="white")
ax4.axvline(wind_clean.mean(), color="tomato", linestyle="--",
            linewidth=1.2, label=f"Mittelwert: {wind_clean.mean():.2f} m/s")
ax4.axvline(wind_clean.median(), color="orange", linestyle="--",
            linewidth=1.2, label=f"Median: {wind_clean.median():.2f} m/s")
ax4.set_title("Verteilung der Windgeschwindigkeit", fontsize=12)
ax4.set_xlabel("m/s")
ax4.set_ylabel("Häufigkeit")
ax4.legend()

# ── Plot 5: Boxplot pro Jahrzehnt ────────────────────────────
ax5 = fig.add_subplot(gs[3, 0])
wind_df["Jahrzehnt"] = (wind_df.index.year // 10) * 10
jahrzehnte = sorted(wind_df["Jahrzehnt"].unique())
data_per_decade = [wind_df[wind_df["Jahrzehnt"] == j]["FM"].values
                   for j in jahrzehnte]
ax5.boxplot(data_per_decade, labels=[str(j)+"s" for j in jahrzehnte],
            patch_artist=True,
            boxprops=dict(facecolor="steelblue", alpha=0.7))
ax5.set_title("Windgeschwindigkeit pro Jahrzehnt (Boxplot)", fontsize=12)
ax5.set_ylabel("m/s")
ax5.set_xlabel("Jahrzehnt")

# ── Plot 6: Rollender Mittelwert ─────────────────────────────
ax6 = fig.add_subplot(gs[3, 1])
rolling_365 = wind_clean.rolling(window=365, center=True).mean()
ax6.plot(wind_clean, linewidth=0.3, color="steelblue", alpha=0.4, label="Tagesmittel")
ax6.plot(rolling_365, linewidth=1.5, color="tomato", label="365-Tage Mittelwert")
ax6.set_title("Rollender 365-Tage Mittelwert", fontsize=12)
ax6.set_ylabel("m/s")
ax6.set_xlabel("Jahr")
ax6.legend()

plt.suptitle("Datenvisualisierung – Windgeschwindigkeit Würzburg (FM)",
             fontsize=15, fontweight="bold", y=1.01)
plt.show()

# STATIONARITÄTSTESTS – Wind (FM)

from statsmodels.tsa.stattools import adfuller, kpss
import warnings
warnings.filterwarnings("ignore")

# ── ADF Test ─────────────────────────────────────────────────
adf_result = adfuller(wind_clean, autolag="AIC")

print(" Augmented Dickey-Fuller Test (ADF) ")
print(f"H0: Die Zeitreihe hat eine Einheitswurzel (nicht stationär)")
print(f"H1: Die Zeitreihe ist stationär\n")
print(f"  Teststatistik:    {adf_result[0]:.4f}")
print(f"  p-Wert:           {adf_result[1]:.4f}")
print(f"  Lags verwendet:   {adf_result[2]}")
print(f"  Kritische Werte:")
for key, val in adf_result[4].items():
    print(f"    {key}: {val:.4f}")
if adf_result[1] < 0.05:
    print(f"\n  → p < 0.05: H0 wird abgelehnt ✅ Zeitreihe ist stationär")
else:
    print(f"\n  → p > 0.05: H0 wird nicht abgelehnt ❌ Zeitreihe ist nicht stationär")

# ── KPSS Test ────────────────────────────────────────────────
kpss_result = kpss(wind_clean, regression="c", nlags="auto")

print("\n KPSS Test ")
print(f"H0: Die Zeitreihe ist stationär")
print(f"H1: Die Zeitreihe ist nicht stationär\n")
print(f"  Teststatistik:    {kpss_result[0]:.4f}")
print(f"  p-Wert:           {kpss_result[1]:.4f}")
print(f"  Lags verwendet:   {kpss_result[2]}")
print(f"  Kritische Werte:")
for key, val in kpss_result[3].items():
    print(f"    {key}: {val:.4f}")
if kpss_result[1] > 0.05:
    print(f"\n  → p > 0.05: H0 wird nicht abgelehnt ✅ Zeitreihe ist stationär")
else:
    print(f"\n  → p < 0.05: H0 wird abgelehnt ❌ Zeitreihe ist nicht stationär")

"""Stationaritätstests prüfen in der Zeitreihenanalyse, ob statistische Eigenschaften wie Mittelwert und Varianz über die Zeit konstant bleiben. Dies ist entscheidend für verlässliche Prognosemodelle, da nicht-stationäre Daten oft zu falschen Ergebnissen führen. Die gängigsten Methoden sind visuelle Inspektion (Plots), der Augmented Dickey-Fuller (ADF) Test und der KPSS-Test."""

# Schwache Stationalität ──> erste Differenz bilden
wind_diff = wind_clean.diff().dropna()

# ── ADF auf differenzierte Reihe ─────────────────────────────
adf_diff = adfuller(wind_diff, autolag="AIC")
kpss_diff = kpss(wind_diff, regression="c", nlags="auto")

print("=== Tests auf differenzierte Reihe (d=1) ===\n")
print(f"ADF  p-Wert:  {adf_diff[1]:.4f} → {'✅ Stationär' if adf_diff[1] < 0.05 else '❌ Nicht stationär'}")
print(f"KPSS p-Wert:  {kpss_diff[1]:.4f} → {'✅ Stationär' if kpss_diff[1] > 0.05 else '❌ Nicht stationär'}")

# ── Plot zum Vergleich ───────────────────────────────────────
fig, axes = plt.subplots(2, 1, figsize=(14, 6))
axes[0].plot(wind_clean, linewidth=0.4, color="steelblue")
axes[0].set_title("Original Zeitreihe")
axes[0].set_ylabel("m/s")

axes[1].plot(wind_diff, linewidth=0.4, color="tomato")
axes[1].set_title("Differenzierte Zeitreihe (d=1)")
axes[1].set_ylabel("Δm/s")
plt.tight_layout()
plt.show()

"""Was bedeutet d=1?
Es bedeutet dass deine Zeitreihe einen schwachen Trend hat der durch einmaliges Differenzieren entfernt wird. Die differenzierte Reihe zeigt die tägliche Veränderung der Windgeschwindigkeit statt der absoluten Werte.
"""

# ACF und PACF auf der differenzierten Reihe (d=1)
fig, axes = plt.subplots(2, 1, figsize=(14, 8))
plot_acf(wind_diff, lags=40, ax=axes[0],
         title="ACF – Windgeschwindigkeit differenziert (d=1)")
plot_pacf(wind_diff, lags=40, ax=axes[1],
          title="PACF – Windgeschwindigkeit differenziert (d=1)",
          method="ywm")
plt.tight_layout()
plt.show()

# SCHRITT 4C: ARIMA MODELLSELEKTION (Grid Search) – Wind (FM)

from itertools import product
from statsmodels.tsa.arima.model import ARIMA
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

print("=== Grid Search ARIMA(p, d, q) ===\n")
print("Suche über p ∈ {0,1,2,3}, d ∈ {0,1}, q ∈ {0,1,2,3}...\n")

results = []

for p, d, q in product(range(4), [1], range(4)):
    try:
        model = ARIMA(wind_clean, order=(p, d, q))
        fit = model.fit()
        results.append({
            "Ordnung (p,d,q)": f"({p},{d},{q})",
            "AIC": round(fit.aic, 2),
            "BIC": round(fit.bic, 2),
            "HQIC": round(fit.hqic, 2)
        })
    except Exception:
        continue

# Nach AIC sortieren
results_df = pd.DataFrame(results).sort_values("AIC").reset_index(drop=True)

print("=== Top 10 Modelle nach AIC ===\n")
print(results_df.head(10).to_string(index=False))

best_order_str = results_df.iloc[0]["Ordnung (p,d,q)"]
print(f"\n→ Bestes Modell nach AIC: ARIMA{best_order_str}")

"""AIC - AIC Akaike Information Criterion, SC - BIC Schwarz Criterion (= Bayesian Information Criterion), HQ - HQIC Hannan-Quinn Information Criterion

ARIMA(3, 1, 2) bedeutet:

p = 3 → Das Modell nutzt die letzten 3 Tage als Eingabe (AR-Teil)
d = 1 → Die Reihe wurde einmal differenziert (Trend entfernt)
q = 2 → Die letzten 2 Vorhersagefehler werden korrigiert (MA-Teil)
"""

# SCHRITT 4D: MODELL SCHÄTZEN & DIAGNOSTIK – Wind (FM)


from statsmodels.stats.diagnostic import acorr_ljungbox
from statsmodels.graphics.tsaplots import plot_acf
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# ── Bestes Modell fitten ─────────────────────────────────────
# Passe p, d, q entsprechend dem Ergebnis aus 4C an!
best_order = (3,1,2)   # ← wird nach Grid Search angepasst

print(f"=== Modell ARIMA{best_order} wird geschätzt ===\n")
model = ARIMA(wind_clean, order=best_order)
fit = model.fit()

# ── Koeffizienten und t-Statistiken ─────────────────────────
print("=== Geschätzte Koeffizienten ===\n")
print(f"{'Koeffizient':<15} {'Schätzer':>10} {'t-Statistik':>12} {'p-Wert':>10} {'Signifikanz':>12}")
print("-" * 65)
for name in fit.params.index:
    p_val = fit.pvalues[name]
    sig = "***" if p_val < 0.01 else ("**" if p_val < 0.05 else ("*" if p_val < 0.1 else ""))
    print(f"{name:<15} {fit.params[name]:>10.4f} {fit.tvalues[name]:>12.4f} {p_val:>10.4f} {sig:>12}")
print("\nSignifikanzniveaus: * p<0.1  ** p<0.05  *** p<0.01")

# ── Residualdiagnostik ───────────────────────────────────────
residuals = pd.Series(fit.resid).dropna()

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

axes[0].plot(residuals, linewidth=0.5, color="steelblue")
axes[0].axhline(0, color="tomato", linestyle="--", linewidth=0.8)
axes[0].set_title("Residuen über Zeit")

plot_acf(residuals, lags=30, ax=axes[1], title="ACF der Residuen")

axes[2].hist(residuals, bins=40, color="steelblue",
             alpha=0.7, edgecolor="white")
axes[2].set_title("Verteilung der Residuen")

plt.tight_layout()
plt.show()

# ── Ljung-Box Test ───────────────────────────────────────────
lb = acorr_ljungbox(residuals, lags=[10, 20, 30], return_df=True)
print("\n=== Ljung-Box Test (H0: keine Autokorrelation in Residuen) ===\n")
print(lb.to_string())
if (lb["lb_pvalue"] > 0.05).all():
    print("\n→ p > 0.05 für alle Lags ✅ Residuen sind unkorrelliert → Modell gut spezifiziert")
else:
    print("\n→ p < 0.05 ❌ Residuen zeigen noch Autokorrelation → Modell anpassen")

# SCHRITT 4E: PROGNOSE – Wind (FM)


import matplotlib.pyplot as plt
import pandas as pd

print("=== 10-Perioden Prognose ===\n")

# ── Prognose berechnen ───────────────────────────────────────
forecast_obj = fit.get_forecast(steps=10)
fc_mean = forecast_obj.predicted_mean
fc_ci = forecast_obj.conf_int(alpha=0.05)
fc_ci.columns = ["Unteres 95% KI", "Oberes 95% KI"]

# ── Prognosetabelle ──────────────────────────────────────────
fc_df = pd.concat([fc_mean.rename("Prognose"), fc_ci], axis=1).round(4)
print(fc_df.to_string())

# ── Plot ─────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(14, 5))

# Letzte 100 Tage als Kontext
ax.plot(wind_clean[-100:], linewidth=0.8,
        color="steelblue", label="Historisch (letzte 100 Tage)")

# Prognose
ax.plot(fc_df["Prognose"], color="tomato",
        linewidth=2, marker="o", label="Prognose")

# Konfidenzintervall
ax.fill_between(fc_df.index,
                fc_df["Unteres 95% KI"],
                fc_df["Oberes 95% KI"],
                alpha=0.3, color="tomato", label="95% Konfidenzintervall")

ax.set_title("10-Tage Prognose – Windgeschwindigkeit Würzburg (FM)", fontsize=13)
ax.set_ylabel("m/s")
ax.set_xlabel("Datum")
ax.legend()
plt.tight_layout()
plt.show()

"""
Windgeschwindigkeit ist eine stark stochastische Größe mit hoher täglicher Variabilität (σ = 1.72 m/s). Das ARIMA(3,1,2) Modell konvergiert bereits nach wenigen Perioden gegen den langfristigen Mittelwert, da vergangene Windwerte nur eine sehr kurze Gedächtnisstruktur aufweisen. Dies ist kein Modellversagen, sondern ein Ausdruck der inhärenten Unvorhersehbarkeit von Windgeschwindigkeit über längere Zeithorizonte. Für präzisere Windprognosen wären physikalische Atmosphärenmodelle erforderlich."""